# values.yaml
postgresql:
  postgresqlPassword: Aushsja34dfgh9345kd
  postgresqlUsername: devsecops
  postgresqlDatabase: devsecops
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"